# -*- coding: utf-8 -*

"""
Class that encapsulates a Stars Archive
Wiki Page's writer/updater
"""

from datetime import datetime, timezone


# Writing all starviews to stars archive wiki page
def execute(starsArchiveWikiPage, starViews):
    pageMarkdown = '# **Star Archive**\n\n'
    pageMarkdown += (
                '_Automatically generated by u/beezassistant on ' +
                datetime.now(timezone.utc).strftime(
                    "%b %d %Y at %H:%M UTC"
                ) + '_\n\n'
    )

    for starView in starViews:
        pageMarkdown += (starView.getViewMarkdown() + '\n\n')

    starsArchiveWikiPage.edit(pageMarkdown)
