# -*- coding: utf-8 -*

"""
Program that archives Scene Info on a
Stars Archive wiki page according to
the provided StarViews
"""

from datetime import datetime, timezone


def execute(starsArchiveWikiPage, starViews):
    """Execute the program"""

    pageMarkdown = '# **Star Archive**\n\n'
    pageMarkdown += (
                '_Automatically generated by u/beezassistant on ' +
                datetime.now(timezone.utc).strftime(
                    "%b %d %Y at %H:%M UTC"
                ) + '_\n\n'
    )

    for starView in starViews:
        pageMarkdown += (starView.getViewMarkdown + '\n\n')

    starsArchiveWikiPage.edit(pageMarkdown)
